name: Test Scheduling Wed and Manual

on:
  schedule:
    - cron: '0 * * * 5'
  workflow_dispatch:

jobs:
  echo:
    name: Echo Job
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo "This should run on Wednesdays and when manually triggered."
